{% set version = '0.9.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mclogit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mclogit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mclogit/mclogit_{{ version }}.tar.gz
  sha256: 9adc5f6d8649960abe009c30d9b4c448ff7d174c455a594cbf104a33d5a36f69

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-memisc
  run:
    - r-base
    - r-matrix
    - r-memisc

test:
  commands:
    - $R -e "library('mclogit')"           # [not win]
    - "\"%R%\" -e \"library('mclogit')\""  # [win]

about:
  home: https://www.elff.eu/software/mclogit/
  dev_url: https://github.com/melff/mclogit/
  license: GPL-2.0-or-later
  summary: Provides estimators for multinomial logit models in their conditional logit and baseline
    logit variants, with or without random effects, with or without overdispersion.
    Random effects models are estimated using the PQL technique (based on a Laplace
    approximation) or the MQL technique (based on a Solomon-Cox approximation). Estimates
    should be treated with caution if the group sizes are small.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mclogit
# Type: Package
# Title: Multinomial Logit Models, with or without Random Effects or Overdispersion
# Version: 0.9.6
# Date: 2022-10-27
# Author: Martin Elff
# Maintainer: Martin Elff <mclogit@elff.eu>
# Description: Provides estimators for multinomial logit models in their conditional logit and baseline logit variants, with or without random effects, with or without overdispersion. Random effects models are estimated using the PQL technique (based on a Laplace approximation) or the MQL technique (based on a Solomon-Cox approximation). Estimates should be treated with caution if the group sizes are small.
# License: GPL-2
# Depends: stats, Matrix
# Imports: memisc, methods
# Suggests: MASS, nnet
# Enhances: emmeans
# LazyLoad: Yes
# URL: http://mclogit.elff.eu,https://github.com/melff/mclogit/
# BugReports: https://github.com/melff/mclogit/issues
# RoxygenNote: 7.1.2
# NeedsCompilation: no
# Packaged: 2022-10-27 09:17:22 UTC; elff
# Repository: CRAN
# Date/Publication: 2022-10-27 10:02:37 UTC
